version: "3.9"
services:
  web:
    container_name: nginx
    image: "nginx:stable-bullseye"
    ports:
      - "80:80"
    volumes:
      - "./src/web:/usr/share/nginx/html"
      - "./work:/work"
    working_dir: /usr/share/nginx/html
    tty: true
  app:
    container_name: "nodejs"
    image: node:20-bullseye
    ports:
      - "3000:3000"
    volumes:
      - "./src/node:/app"
      - "./work:/work"
    working_dir: /app
    tty: true
  db:
    container_name: "postgres"
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./work:/work"
    working_dir: /work
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
      - "./work:/work"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - db
